### ISSUE TITLE
unable to install arctic on windows machine.

### ISSUE THREAD

**Issue by kwtneo** [manahl/arctic#332] opened 2017-03-06 14:22 UTC
#### Arctic Version
1.41
```
# Arctic version here
```

#### Arctic Store

```
# VersionStore, TickStore, or ChunkStore
```

#### Platform and version

Windows 7 Professional, 64 bit

#### Description of problem and/or code sample that reproduces the issue
Hi Team, running into some issues with the installation. Things are ok and the compiler throws off a lot of warnings but then it hits this:
 src/python-lz4.c(131) : error C2143: syntax error : missing ';' before 'type'
    src/python-lz4.c(133) : error C2065: 'actual_size' : undeclared identifier
    src/python-lz4.c(134) : error C2065: 'actual_size' : undeclared identifier
    src/python-lz4.c(136) : error C2065: 'actual_size' : undeclared identifier
    src/python-lz4.c(178) : warning C4127: conditional expression is constant
    src/python-lz4.c(178) : warning C4127: conditional expression is constant
    src/python-lz4.c(220) : warning C4127: conditional expression is constant
    src/python-lz4.c(225) : warning C4127: conditional expression is constant
    src/python-lz4.c(225) : warning C4127: conditional expression is constant
    src/python-lz4.c(265) : warning C4127: conditional expression is constant
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\Bin\\x86_amd64\\cl.ex
e' failed with exit status 2

bigger Log reproduced here. Any help would be appreciated. thanks!

C:\Python34>pip install git+https://github.com/manahl/arctic.git
Collecting git+https://github.com/manahl/arctic.git
  Cloning https://github.com/manahl/arctic.git to c:\users\user\appdata\local\temp\pip-hbcrwvsi-build
Requirement already satisfied: decorator in c:\python34\lib\site-packages (from arctic==1.41.0)
Requirement already satisfied: enum34 in c:\python34\lib\site-packages (from arctic==1.41.0)
Collecting lz4 (from arctic==1.41.0)
  Using cached lz4-0.8.2.tar.gz
Collecting mockextras (from arctic==1.41.0)
  Using cached mockextras-1.0.2-py3-none-any.whl
Requirement already satisfied: pandas in c:\python34\lib\site-packages (from arctic==1.41.0)
Collecting pymongo>=3.0 (from arctic==1.41.0)
  Using cached pymongo-3.4.0-cp34-none-win_amd64.whl
Requirement already satisfied: python-dateutil in c:\python34\lib\site-packages (from arctic==1.41.0
)
Requirement already satisfied: pytz in c:\python34\lib\site-packages (from arctic==1.41.0)
Collecting tzlocal (from arctic==1.41.0)
  Using cached tzlocal-1.3.tar.gz
Requirement already satisfied: numpy>=1.7.0 in c:\python34\lib\site-packages (from pandas->arctic==1
.41.0)
Requirement already satisfied: six>=1.5 in c:\python34\lib\site-packages (from python-dateutil->arct
ic==1.41.0)
Installing collected packages: lz4, mockextras, pymongo, tzlocal, arctic
  Running setup.py install for lz4 ... error
    Complete output from command c:\python34\python.exe -u -c "import setuptools, tokenize;__file__=
'C:\\Users\\user\\AppData\\Local\\Temp\\pip-build-l1_nmots\\lz4\\setup.py';f=getattr(tokenize, 'open
', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'
))" install --record C:\Users\user\AppData\Local\Temp\pip-i8ftgmmg-record\install-record.txt --singl
e-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'lz4' extension
    creating build
    creating build\temp.win-amd64-3.4
    creating build\temp.win-amd64-3.4\Release
    creating build\temp.win-amd64-3.4\Release\src
    C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Bin\x86_amd64\cl.exe /c /nologo /Ox /MD /
W3 /GS- /DNDEBUG -DVERSION=\"0.8.2\" -DLZ4_VERSION=\"r131\" -Ic:\python34\include -Ic:\python34\incl
ude /Tcsrc/lz4.c /Fobuild\temp.win-amd64-3.4\Release\src/lz4.obj /Ot /Wall
    lz4.c
    c:\users\user\appdata\local\temp\pip-build-l1_nmots\lz4\src\lz4.h(316) : warning C4668: '__GNUC_
_' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
    c:\users\user\appdata\local\temp\pip-build-l1_nmots\lz4\src\lz4.h(316) : warning C4668: '__GNUC_
MINOR__' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
    c:\users\user\appdata\local\temp\pip-build-l1_nmots\lz4\src\lz4.h(318) : warning C4668: '__GNUC_
_' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
    c:\users\user\appdata\local\temp\pip-build-l1_nmots\lz4\src\lz4.h(318) : warning C4668: '__GNUC_
MINOR__' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
.
.
.bunch of other warnings
.
.
.
    c:\program files (x86)\microsoft visual studio 10.0\vc\include\codeanalysis\sourceannotations.h(
91) : warning C4820: 'PreAttribute' : '4' bytes padding added after data member 'Access'
    c:\program files (x86)\microsoft visual studio 10.0\vc\include\codeanalysis\sourceannotations.h(
106) : warning C4820: 'PreAttribute' : '4' bytes padding added after data member 'NullTerminated'
    c:\program files (x86)\microsoft visual studio 10.0\vc\include\codeanalysis\sourceannotations.h(
122) : warning C4820: 'PostAttribute' : '4' bytes padding added after data member 'Access'
    c:\program files (x86)\microsoft visual studio 10.0\vc\include\codeanalysis\sourceannotations.h(
201) : warning C4820: 'PreRangeAttribute' : '4' bytes padding added after data member 'Deref'
    c:\program files (x86)\microsoft visual studio 10.0\vc\include\codeanalysis\sourceannotations.h(
213) : warning C4820: 'PostRangeAttribute' : '4' bytes padding added after data member 'Deref'
    C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Include\malloc.h(62) : warning C4820: '_h
eapinfo' : '4' bytes padding added after data member '_useflag'
    C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Include\smmintrin.h(77) : warning C4668:
'__cplusplus' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
    C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Include\nmmintrin.h(30) : warning C4668:
'__cplusplus' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
    C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Include\wmmintrin.h(29) : warning C4668:
'__cplusplus' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
    C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Include\intrin.h(1015) : warning C4255: '
__getcallerseflags' : no function prototype given: converting '()' to '(void)'
    src/lz4.c(92) : warning C4668: '__GNUC__' is not defined as a preprocessor macro, replacing with
 '0' for '#if/#elif'
    src/lz4.c(92) : warning C4668: '__GNUC_MINOR__' is not defined as a preprocessor macro, replacin
g with '0' for '#if/#elif'
    src/lz4.c(92) : warning C4668: '__INTEL_COMPILER' is not defined as a preprocessor macro, replac
ing with '0' for '#if/#elif'
    src/lz4.c(356) : warning C4820: '<unnamed-tag>' : '4' bytes padding added after data member 'dic
tSize'
    src/lz4.c(373) : warning C4255: 'LZ4_sizeofState' : no function prototype given: converting '()'
 to '(void)'
    src/lz4.c(1474) : warning C4255: 'LZ4_sizeofStreamState' : no function prototype given: converti
ng '()' to '(void)'
    c:\users\user\appdata\local\temp\pip-build-l1_nmots\lz4\src\lz4.c(154) : warning C4711: function
 'LZ4_isLittleEndian' selected for automatic inline expansion
    c:\users\user\appdata\local\temp\pip-build-l1_nmots\lz4\src\lz4.c(156) : warning C4711: function
 'LZ4_read16' selected for automatic inline expansion
    c:\users\user\appdata\local\temp\pip-build-l1_nmots\lz4\src\lz4.c(167) : warning C4711: function
 
    c:\python34\include\import.h(119) : warning C4820: '_frozen' : '4' bytes padding added after dat
a member 'size'
    c:\python34\include\code.h(18) : warning C4820: '<unnamed-tag>' : '4' bytes padding added after
data member 'co_flags'
    c:\python34\include\code.h(29) : warning C4820: '<unnamed-tag>' : '4' bytes padding added after
data member 'co_firstlineno'
    c:\users\user\appdata\local\temp\pip-build-l1_nmots\lz4\src\lz4.h(316) : warning C4668: '__GNUC_
_' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
    c:\users\user\appdata\local\temp\pip-build-l1_nmots\lz4\src\lz4.h(316) : warning C4668: '__GNUC_
MINOR__' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
    c:\users\user\appdata\local\temp\pip-build-l1_nmots\lz4\src\lz4.h(318) : warning C4668: '__GNUC_
_' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
    c:\users\user\appdata\local\temp\pip-build-l1_nmots\lz4\src\lz4.h(318) : warning C4668: '__GNUC_
MINOR__' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
    C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Include\stdint.h(105) : warning C4668: '_
INTPTR' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
    src/python-lz4.c(76) : warning C4100: 'self' : unreferenced formal parameter
    src/python-lz4.c(131) : error C2143: syntax error : missing ';' before 'type'
    src/python-lz4.c(133) : error C2065: 'actual_size' : undeclared identifier
    src/python-lz4.c(134) : error C2065: 'actual_size' : undeclared identifier
    src/python-lz4.c(136) : error C2065: 'actual_size' : undeclared identifier
    src/python-lz4.c(178) : warning C4127: conditional expression is constant
    src/python-lz4.c(178) : warning C4127: conditional expression is constant
    src/python-lz4.c(220) : warning C4127: conditional expression is constant
    src/python-lz4.c(225) : warning C4127: conditional expression is constant
    src/python-lz4.c(225) : warning C4127: conditional expression is constant
    src/python-lz4.c(265) : warning C4127: conditional expression is constant
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\Bin\\x86_amd64\\cl.ex
e' failed with exit status 2

    ----------------------------------------
Command "c:\python34\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\user\\AppDat
a\\Local\\Temp\\pip-build-l1_nmots\\lz4\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=
f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\
Users\user\AppData\Local\Temp\pip-i8ftgmmg-record\install-record.txt --single-version-externally-man
aged --compile" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-build-l1_nmots\lz4\

C:\Python34>

**Comment by bmoscon** [comment] 2017-03-06 14:23
only Linux is officially supported. Some people have gotten windows working. See issue #6

**Comment by bmoscon** [comment] 2017-03-06 14:24
closing as a dupe of #6

**Closed by bmoscon** 2017-03-06 14:24 UTC

**Comment by kwtneo** [comment] 2017-03-06 14:28
great. thanks guys!
