### ISSUE TITLE
Append and upsert

### ISSUE THREAD

**Issue by simonfunston** [manahl/arctic#110] opened 2016-03-15 17:49 UTC
I expected append with upsert = True to check if the datetime index exists in the cache, insert it if not and update it if it exists, but it always just appends, is this a bug?

For example if I insert a datafrmae with a datetime index from 1st to 31st of Jan with upsert as True twice, the data is duplicated rather updating existing or doing nothing.

**Comment by richardbounds** [comment] 2016-03-24 08:12
That's intended - append() always appends, but it should raise an error if upsert=False and the item doesn't already exist.

**Comment by bmoscon** [comment] 2016-04-04 13:10
mongo and arctic in turn don't have the same concept of indexed dataframes as pandas does. If you call append, it will append that data to the existing data. It won't go and check if those indexes already exist or not. If you need to update something  you'll need to read out all the data for that symbol, edit the dataframe and then rewrite it. Appending is only for adding data, not for updating data.

**Comment by bmoscon** [comment] 2016-08-05 13:47
FYI - the new storage type, ChunkStore supports updating dataframes in place. Its append functionality will still do what VersionStore does (i.e. append is not idempotent), but update is idempotent.

**Comment by bmoscon** [comment] 2016-08-06 17:34
I'm closing this. This is definitely working as designed. If anything, its a documentation issue, but there is already an issue open for that. So this is another +1 for releasing some documentation see #3

**Closed by bmoscon** 2016-08-06 17:34 UTC
