### ISSUE TITLE
python3 - strings gets converted to bytes

### ISSUE THREAD

**Issue by harishmk** [manahl/arctic#598] opened 2018-08-03 20:42 UTC
#### Arctic Version

```
1.68.0
```

#### Arctic Store

```
VersionStore
```

#### Platform and version

Microsoft Windows [Version 10.0.16299.431]

#### Description of problem and/or code sample that reproduces the issue

A dataframe with columns of type str was written using python 2.7.5 and arctic 1.68.0
Reading back using python 2.7.5 and arctic 1.68.0 returns the columns of type str.

but reading with python3 and arctic 1.68.0 changes the string columns to bytes
same as [https://github.com/manahl/arctic/issues/64](https://github.com/manahl/arctic/issues/64)?

**Comment by bmoscon** [comment] 2018-08-03 20:53
We used to do this manually in our lz4 code. Since we dropped that in favor of another library, we'll have to do this in arctic manually for strings

**Comment by harishmk** [comment] 2018-08-06 14:36
i am doing this for now:
```
for c in df.select_dtypes(object):
    if type(df[c].iloc[0]) == bytes:
        df[c] = df[c].str.decode('utf-8')
```
same fix for index also.
not sure about multi-index, but we don't have any at the moment.

**Comment by bmoscon** [comment] 2018-09-05 22:50
Hm, can you provide a complete code sample or some other example that reproduces the issue? With python 3.6.6 this produces columns that are `str`:

```
   df = pd.DataFrame({'data': ['string1', 'string2'], 'date': [dt(2015,1,1), dt(2015,1,2)]})
    df.set_index('date', inplace=True)
    library.write('test', df)
    df = library.read('test').data
    print(df)
    print(type(df['data'].iloc[0]))
```

**Comment by harishmk** [comment] 2018-09-06 00:55
will try to get a sample code...but did you try creating the dataframe with python 2.7.5 and reading it back with python 3?

**Comment by bmoscon** [comment] 2018-11-17 01:19
i did not try that (write with py2 read with py3)

**Comment by shashank88** [comment] 2019-04-02 16:48
Similar issues reported internally. I think with the adoption of py3 internally, this issue might get worse:
```2 issues: indices being saved in Py2 come out as bytes and we can't slice and dice anymore
and 2nd issue that columns of string type sometimes come out as byte
for our upgrade I thought of loading and resaving all related dataframes converting all strings to unicode
that should work in Py3 as well
but will be a lot of work
having something on the arctic layer would be much better```

**Comment by bmoscon** [comment] 2019-04-03 19:15
Its an LZ4 thing, so we'll need to write custom code that converts everything (like we used to do internally before we dropped our own LZ4 C module)

**Comment by shashank88** [comment] 2019-04-05 19:58
Sorry I am not that aware of the lz4 C thingy. If I understand correctly we lose the encoding when we provide the bytes to the lz4 compress and hence it always decompresses to bytes in py3 and can cause issues when any char is not ascii?

**Comment by shashank88** [comment] 2019-04-23 21:51
@bmoscon am starting to work on this as some teams are blocked on migration to python3 due to this issue. I am not aware of the history of the lz4 thing, but is my understanding above correct? If so, what's the place where the custom code will live? Is it just after decompressing the df?

**Comment by bmoscon** [comment] 2019-04-23 22:21
you'd basically need to do what the OP indicated he was doing. check the type that comes back and convert if needed

**Comment by shashank88** [comment] 2019-05-01 12:24
Closing this as this is resolved with https://github.com/manahl/arctic/pull/757

**Closed by shashank88** 2019-05-01 12:24 UTC
Labels: bug
