### ISSUE TITLE
stock tick data storing tutorial.

### ISSUE THREAD

**Issue by leolle** [manahl/arctic#205] opened 2016-08-30 03:15 UTC
Hi, is there any tutorial for storing tick data and how to update the data for my symbols?

**Comment by bmoscon** [comment] 2016-08-30 11:26
define "update". If you mean continue to add data to a symbol, just keep using "write". tickstore's API is very very simple. You can just keep calling write with new data and it will keep adding that tick data to the symbol.

**Comment by leolle** [comment] 2016-08-31 01:43
> define "update". If you mean continue to add data to a symbol, just keep using "write". tickstore's API is very very simple. You can just keep calling write with new data and it will keep adding that tick data to the symbol.

Thank you @bmoscon . If I don't use timestamp as my tick dataframe index, since I don't have miliseconds on my timestamp, will it still add new data to that same symbol when using "write"? or does my database become x2 x3 times larger on and on?

**Comment by leolle** [comment] 2016-08-31 10:14
@bmoscon btw, how to initialize a tickdata library?
here is my code:

from arctic.tickstore.tickstore import TickStore as ts
store2 = ts('localhost')
store2.initialize_library("tick_lib")

its error is like:
AttributeError                            Traceback (most recent call last)
<ipython-input-442-bf5c4a4f4243> in <module>()
----> 1 import codecs, os;__pyfile = codecs.open('''/tmp/py22825yhb''', encoding='''utf-8''');__code = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/tmp/py22825yhb''');exec(compile(__code, '''/home/weiwu/projects/arctic/storing_tick_data_to_mongodb.py''', 'exec'));

/home/weiwu/projects/arctic/storing_tick_data_to_mongodb.py in <module>()

/home/weiwu/.virtualenvs/arctic/local/lib/python2.7/site-packages/arctic/tickstore/tickstore.pyc in __init__(self, arctic_lib, chunk_size)
    105 
    106         # Do we allow reading from secondaries
--> 107         self._allow_secondary = self._arctic_lib.arctic._allow_secondary
    108 
    109         # The default collections

AttributeError: 'str' object has no attribute 'arctic'

**Comment by bmoscon** [comment] 2016-09-07 12:31
You use Arctic to connect to the database, and you initialize the library with the lib_type as Tickstore, something like

```
from arctic import TICK_STORE
from arctic import Arctic
db = Arctic('localhost')
lib = db.initialize_library('name', lib_type=TICK_STORE)

```


That should work

**Comment by bmoscon** [comment] 2016-09-08 15:44
Does that help @leolle ? After you've done the above, you can just use write to write dataframes or dicts.

**Comment by leolle** [comment] 2016-09-10 15:16
> Does that help @leolle ? After you've done the above, you can just use write to write dataframes or dicts.

Hi @bmoscon ,
I tried this method, but I found an issue, I get tick data from csv files from somewhere month by month, there are multiple files for the same ticker, once I write dataframe into the tick store from one file, the data stored will be erased by the newer file on the same tick, please advise how to solve this problem?

**Comment by bmoscon** [comment] 2016-09-12 12:04
@leolle I'm having a hard time figuring out exactly what you are doing. Can you either put some sample code here which reproduces your issue or email me something (my email is on my github profile page) ?

**Comment by bmoscon** [comment] 2016-09-12 12:50
alternatively, @leolle , I've included an example that shows me writing two dataframes, that do not overwrite eachother:

```
from arctic import Arctic, TICK_STORE
import pandas as pd
import pytz as tz
from datetime import datetime as dt


tz = ('US/Eastern')

a = Arctic('localhost')
a.initialize_library('bmoscon.tickstore', lib_type=TICK_STORE)
l = m['bmoscon.tickstore']

df = pd.DataFrame(data={'data': [1,2,3]}, index=[dt(2016,1,1, 1, 1, 1, 1,tz), dt(2016,1,2,1,1,1,1,tz), dt(2016,1,3,1,1,1,1,tz)])

df2 = pd.DataFrame(data={'data': [4,5,6]}, index=[dt(2016,1,4, 1, 1, 1, 1,tz), dt(2016,1,5,1,1,1,1,tz), dt(2016,1,6,1,1,1,1,tz)])

l.write('test', df)
l.read('test')


                           data
2016-01-01 05:57:01+00:00     1
2016-01-02 05:57:01+00:00     2
2016-01-03 05:57:01+00:00     3


l.write('test', df2)
l.read('df')


                           data
2016-01-01 05:57:01+00:00     1
2016-01-02 05:57:01+00:00     2
2016-01-03 05:57:01+00:00     3
2016-01-04 05:57:01+00:00     4
2016-01-05 05:57:01+00:00     5
2016-01-06 05:57:01+00:00     6

```

Hopefully that helps. If not, please send me something that illustrates the issue you are having so I can help you figure out whats wrong.

**Comment by bmoscon** [comment] 2016-09-16 17:16
@leolle still having issues or are you all set?

**Comment by bmoscon** [comment] 2016-09-30 15:53
so this isnt documentation for tickstore, but its still documentation!

https://github.com/manahl/arctic/wiki/Chunkstore

**Comment by bmoscon** [comment] 2016-10-14 02:06
closing since i havent gotten a response on this in some time.

**Closed by bmoscon** 2016-10-14 02:06 UTC

**Comment by haohello** [comment] 2017-09-25 15:06
@bmoscon 
what if the library already exists before calling initialize method??

a = Arctic('localhost')
a.initialize_library('bmoscon.tickstore', lib_type=TICK_STORE)
l = a['bmoscon.tickstore']

**Comment by bmoscon** [comment] 2017-09-25 16:14
if it already exists it doesnt do anything (i.e. it wont delete any data already there)

**Comment by haohello** [comment] 2017-09-25 23:37
@bmoscon  Sorry to bother you again,  I wrote the code as below, but I didn't know how to pass in the mongodb user/pass, also can I write the code like this? 


a = Arctic('10.0.0.19')

a.initialize_library('bmoscon.tickstore', lib_type=TICK_STORE)
l = a['bmoscon.tickstore']

#df = pd.DataFrame(data={'data': [1,2,3]}, index=[dt(2016,1,1, 1, 1, 1, 1,tz), dt(2016,1,2,1,1,1,1,tz), dt(2016,1,3,1,1,1,1,tz)])

#df2 = pd.DataFrame(data={'data': [4,5,6]}, index=[dt(2016,1,4, 1, 1, 1, 1,tz), dt(2016,1,5,1,1,1,1,tz), dt(2016,1,6,1,1,1,1,tz)])

df = pd.DataFrame(data= [104303, 6.87, 6.92], columns=['Time', 'Now', 'High'], index=['Time'])

df2 = pd.DataFrame(data= [104303, 6.77, 6.85], columns=['Time', 'Low', 'Close'], index=['Time'])


l.write('test', df)
l.read('test')


l.write('test', df2)
l.read('df')

**Comment by bmoscon** [comment] 2017-09-26 00:02
in `arctic.auth` there is an auth function you can use:

```
authenticate(db, user, password)
```

**Comment by haohello** [comment] 2017-09-26 02:30
@bmoscon  Any real example how you are using this code?

**Comment by bmoscon** [comment] 2017-09-26 13:13
you can see some slides from the presentation about arctic that one of the original authors did:

https://www.slideshare.net/JamesBlackburn1/2015-pydata-highperformance-iot-and-financial-data-storage-with-python-and-mongodb

he may want to chime in with more details @jamesblackburn 

as far as `db` in the code - its the database name

**Comment by jamesblackburn** [comment] 2017-12-03 21:46
@haohello For hooks it's expected that in your codebase you have some mechanism for getting usernames and passwords to use for logging into the Mongo database.

You can register your handler in hooks.py. You can see how this is used in the top-level arctic.py for creating the mongo connections:

```
                auth = get_auth(self.mongo_host, self._application_name, 'admin')
                if auth:
                    authenticate(self._adminDB, auth.user, auth.password)
```
