### ISSUE TITLE
Build failed in Win64 

### ISSUE THREAD

**Issue by arita37** [manahl/arctic#223] opened 2016-09-14 23:31 UTC
Hello,
Just wondering if there is some conda package available for win64 ?
When installing by pip on windows, I got this failure:

```
    src/python-lz4.c(76) : warning C4100: 'self' : unreferenced formal parameter
    src/python-lz4.c(131) : error C2143: syntax error : missing ';' before 'type'
    src/python-lz4.c(133) : error C2065: 'actual_size' : undeclared identifier
    src/python-lz4.c(134) : error C2065: 'actual_size' : undeclared identifier
    src/python-lz4.c(136) : error C2065: 'actual_size' : undeclared identifier
    src/python-lz4.c(178) : warning C4127: conditional expression is constant
    src/python-lz4.c(178) : warning C4127: conditional expression is constant
    src/python-lz4.c(265) : warning C4127: conditional expression is constant
    error: command 
'C:\\Users\\asus1\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2
    
    ----------------------------------------
Command "D\Anaconda27\python.exe -u -c 
"import setuptools, tokenize;__file__=
'f:\\usertemp\\pip-build-wehayg\\lz4\\setup.py';
exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" 
install --record f:\usertemp\pip-dpqytl-record\install-record.txt 
--single-version-externally-managed 
--compile" failed with error code 1 in f:\usertemp\pip-build-wehayg\lz4\
```

**Comment by bmoscon** [comment] 2016-09-16 16:47
this is a dupe of #6 
It is possible to compile on windows, but its a very manual process.

**Closed by bmoscon** 2016-09-16 16:47 UTC

**Comment by spyamine** [comment] 2016-10-21 15:36
Try to install lz4 64 bit before and then retry
