### ISSUE TITLE
version store, write with prune_previous_version = True still keeps the the previous version

### ISSUE THREAD

**Issue by whumei** [manahl/arctic#204] opened 2016-08-29 19:01 UTC
It seems that prune_previous_version does not work in version store. please see the following sample code. I think with prune_previous_version set to be True, I should only get one version back from list_versions function, or I will get a list of two version back, but one of them should have "deteled" set to be True.

===============================================================

import pandas as pd
import time

data = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
arctic_db.write(symbol='key3', data=data, prune_previous_version=True)
time.sleep(10)
arctic_db.write(symbol='key3', data=data, prune_previous_version=True)

print arctic_db.list_versions('key3')

------------------------------------------------------------------------------------------------
[{'deleted': False, 'date': datetime.datetime(2016, 8, 29, 13, 42, 29, tzinfo=tzfile('/usr/share/zoneinfo/America/Chicago')), 'symbol': u'key3', 'version': 2, 'snapshots': []}, 
{'deleted': False, 'date': datetime.datetime(2016, 8, 29, 13, 42, 19, tzinfo=tzfile('/usr/share/zoneinfo/America/Chicago')), 'symbol': u'key3', 'version': 1, 'snapshots': []}]

**Comment by bmoscon** [comment] 2016-08-30 10:57
not a bug. from the code:

```

def _prune_previous_versions(self, symbol, keep_mins=120):
        """
        Prune versions, not pointed at by snapshots which are at least keep_mins old.
        """
```

so it has to be 2 hours old before being pruned

**Comment by bmoscon** [comment] 2016-09-07 12:32
I'm going to assume I can close this unless I hear from you within the next couple of days

**Comment by bmoscon** [comment] 2016-09-12 12:05
closing. If you'd like to discuss something related to this (like allowing the user to set the prune time) please open a new issue

**Closed by bmoscon** 2016-09-12 12:05 UTC
