### ISSUE TITLE
Feature Request: support writing to TickStore with a generator as input

### ISSUE THREAD

**Issue by ghost** [manahl/arctic#315] opened 2017-01-12 19:49 UTC
#### Arctic Version
```
1.37.0
```

#### Arctic Store

```
TickStore
```

This could be useful if you were streaming tick data in real time, and as I understand would likely be more memory efficient in the general case as well.

**Comment by bmoscon** [comment] 2017-02-01 18:53
Seems reasonable, let me write something up and get back to you.

**Comment by plintX** [comment] 2017-03-24 01:51
Any updates  on this?

**Comment by bmoscon** [comment] 2017-03-24 13:19
nope, I haven't gotten to it yet. We do accept (and love) pull requests :)

**Comment by richardbounds** [comment] 2017-04-05 05:51
The problem is that in order for the compression to be efficient, you have to write relatively large blocks of ticks together. Writing tick-by-tick straight to Arctic just wouldn't really work.

What we do is stream our incoming tick data to Kafka, then offload the data from Kafka to Arctic in batches. All of the tick collectors and kafka2mongo code is written in Java, for performance reasons. Unfortunately we've never had enough spare time to open-source any of it.

**Comment by jeffneuen** [comment] 2017-12-17 22:29
Sorry to revive an old issue, but I have a similar question that is probably best addressed in this thread. When it comes to writing streaming tick data that is relatively low volume (say ~ 1 tick per second), what do you find to be an acceptable batch size? I have run performance comparisons on writing ticks individually (as they would be via real-time streaming) and via batch, and reading the ticks that were written via one large batch are literally thousands of times faster than the individual ticks. If I was dealing with a very high volume tick stream, I could just do something like batch them every 10 seconds and write. However, for the lower volume stream, the problem seems to be trickier. Do you have any suggestions on how to address the problem of writing real-time ticks that are lower volume, but which the user would still like to have real-time(ish) access to?

**Comment by bmoscon** [comment] 2017-12-17 22:33
@jeffneuen greater than 4MB I'd say. The max doc size is about 16MB, so somewhere between 4MB and 16MB as long as the tick window is suitable for you. If its not, you might consider the other storage engines.

**Comment by jeffneuen** [comment] 2017-12-17 22:37
@bmoscon Thanks - yes, that size might make the window too large - I'd be waiting forever to for the queue to fill up enough for a write to get to 4MB. I'll try with VersionStore and see what kind of performance I can obtain. Thanks!

**Comment by bmoscon** [comment] 2017-12-18 14:24
version store will internally keep track of the size of the data and compress it when it reaches a threshold. So i'd try using it for a while before testing the performance

**Comment by bmoscon** [comment] 2018-08-17 12:55
going to close this based on previous comments by richard

**Closed by bmoscon** 2018-08-17 12:55 UTC
