### ISSUE TITLE
Trouble installing with Anaconda

### ISSUE THREAD

**Issue by aclerc** [manahl/arctic#52] opened 2015-11-23 14:44 UTC
Hi, I've heard a bit about arctic and I'm excited to give it a try.  My system is Windows 7 32-bit and I've installed the Anaconda 2.4.0 distribution.

I have read Issue #6 and I think I am having a different problem, I checked C:\Anaconda\Lib\distutils\distutils.cfg and it says compiler=mingw32

Here is the output when I run `pip install git+https://github.com/manahl/arctic.git`
```
Collecting git+https://github.com/manahl/arctic.git
  Cloning https://github.com/manahl/arctic.git to c:\users\aclerc\appdata\local\temp\pip-kxthfn-build
Requirement already satisfied (use --upgrade to upgrade): decorator in c:\anaconda\lib\site-packages (from arctic==1.13.0)
Requirement already satisfied (use --upgrade to upgrade): enum34 in c:\anaconda\lib\site-packages (from arctic==1.13.0)
Requirement already satisfied (use --upgrade to upgrade): lz4 in c:\anaconda\lib\site-packages (from arctic==1.13.0)
Requirement already satisfied (use --upgrade to upgrade): mockextras in c:\anaconda\lib\site-packages (from arctic==1.13.0)
Requirement already satisfied (use --upgrade to upgrade): pandas in c:\anaconda\lib\site-packages (from arctic==1.13.0)
Requirement already satisfied (use --upgrade to upgrade): pymongo>=3.0 in c:\anaconda\lib\site-packages (from arctic==1.13.0)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in c:\anaconda\lib\site-packages (from arctic==1.13.0)
Requirement already satisfied (use --upgrade to upgrade): pytz in c:\anaconda\lib\site-packages (from arctic==1.13.0)
Requirement already satisfied (use --upgrade to upgrade): tzlocal in c:\anaconda\lib\site-packages (from arctic==1.13.0)
Requirement already satisfied (use --upgrade to upgrade): mock>=0.8.0 in c:\anaconda\lib\site-packages (from mockextras->arctic==1.13.0)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.0 in c:\anaconda\lib\site-packages (from pandas->arctic==1.13.0)
Installing collected packages: arctic
  Running setup.py install for arctic

... more install messages which look fine ...

running build_ext
    cythoning src/_compress.pyx to src\_compress.c
    building 'arctic._compress' extension
    creating build\temp.win32-2.7
    creating build\temp.win32-2.7\Release
    creating build\temp.win32-2.7\Release\src
    C:\Anaconda\Scripts\gcc.bat -mdll -O -Wall -IC:\Anaconda\include -IC:\Anaconda\PC -c src\_compress.c -o build\temp.win32-2.7\Release\src\_compress.o -fopenmp
    src\_compress.c:259:17: fatal error: omp.h: No such file or directory
    compilation terminated.
    warning: src\_compress.pyx:167:38: Use boundscheck(False) for faster access
    warning: src\_compress.pyx:177:19: Use boundscheck(False) for faster access
    warning: src\_compress.pyx:29:5: Cannot profile nogil function.
    warning: src\_compress.pyx:35:5: Cannot profile nogil function.
    warning: View.MemoryView:288:5: Cannot profile nogil function.

... more warnings related to nogil ...

    error: command 'C:\\Anaconda\\Scripts\\gcc.bat' failed with exit status 1
```

it seems gcc.bat is the problem, this script contains
```
@echo off
"%~f0\..\..\MinGW\bin\gcc.exe" %*
```

**Comment by jamesblackburn** [comment] 2015-11-23 17:54
The issue is the parallel lz4 cython implementation we provide.  In reality we don't need this:
https://github.com/manahl/arctic/blob/master/arctic/_compression.py#L10
and setting environment: `DISABLE_PARALLEL=true`

So you should find that it just works without needing to build the compression library.  It would be good to provide an option to build without the parallel compression...

**Comment by aclerc** [comment] 2015-11-24 14:32
Thanks very much for your reply, James.  I've created an environment variable called DISABLE_PARALLEL and set it to true, in Python `not os.environ.get('DISABLE_PARALLEL')` now returns `False` instead of `True`.

setup.py is still failing in the way described at the beginning of this Issue but I find I can now just import arctic and start using its classes. I was working through arctic/howtos/how_to_use_arctic.py but ran in to an error on the first read (line 27, `library.read('SYMBOL')`)

```
File "<string>", line 1
    (
    ^
SyntaxError: unexpected EOF while parsing
```

Using mongo I can see that each time I use the `library.write` method, a new document appears in the scratch collection so it seems things are somewhat working.  Do you know what might be causing the SyntaxError when I try to use `library.read`?

Also could you please explain how I can I install arctic without building the compression library?

Thank you for your help!

**Comment by jamesblackburn** [comment] 2015-11-25 13:20
I'm not sure how you can get that error, what was the full backtrace?

These howtos are tested as part of the build process and they're known to work. I suspect that you're in a bit of uncharted territory running on Windows. @beartastic got this to work in #6 perhaps they can offer some advice?

**Comment by bmoscon** [comment] 2015-12-06 14:02
@aclerc this seems related to issue #37 

Once my pull request goes through please update and try it again. It should work for you

**Comment by jamesblackburn** [comment] 2015-12-11 16:34
@aclerc can you retry? @bmoscon's pull request has now been merged

**Comment by jamesblackburn** [comment] 2015-12-11 16:37
The issue with newer Numpy has been fixed by @bmoscon 

Issues with running on Windows are tracked by issue #6 

Do let us know how you get on

**Closed by jamesblackburn** 2015-12-11 16:37 UTC

**Comment by lJoublanc** [comment] 2016-10-03 14:50
For other people using Anaconda and ending up at this page, just wanted to add that in order to disable parallel compression as per the comments above,  you can modify `setup.py` and comment out the **two** relevant 'compress' references like so:
```

# Cython lz4
#compress = Extension('arctic._compress',
#                     sources=["src/_compress.pyx", "src/lz4.c", "src/lz4hc.c"],
#                     extra_compile_args=['-fopenmp'],
#                     extra_link_args=['-fopenmp'])
#
setup(
    name="arctic",
    version="1.32.0",
    author="Man AHL Technology",
    author_email="ManAHLTech@ahl.com",
    description=("AHL Research Versioned TimeSeries and Tick store"),
    license="GPL",
    keywords=["ahl", "keyvalue", "tickstore", "mongo", "timeseries", ],
    url="https://github.com/manahl/arctic",
    packages=find_packages(exclude=['tests', 'tests.*', 'benchmarks']),
    long_description='\n'.join((long_description, changelog)),
    cmdclass={'test': PyTest},
    #ext_modules=cythonize(compress),  # <<<<<< Comment this line and above.
    setup_requires=["Cython",
                    "numpy",
```

and this will allow you to build without the parallel compressor. Changing the `DISABLE_PARALLEL` environment variable doesn't affect the build, as far as I can see.

**Comment by hj1234** [comment] 2018-05-14 15:01
Having encountered an error when trying to run arctic following a regular pip instal:


```
from arctic import Arctic

ImportError: DLL load failed: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail)
``` 


I tried cloning the git and updating the setup.py file as described above. However, now when I run the package I get:

`
` ImportError: cannot import name _compress
`

version: 1.66
running: windows 7, python 2.7 (anaconda)

Any help really appreciated!
