### ISSUE TITLE
error: Setup script exited with platform cygwin is not supported

### ISSUE THREAD

**Issue by smad22** [manahl/arctic#257] opened 2016-10-14 01:13 UTC
Please advise on the above.  Thanks.

**Comment by bmoscon** [comment] 2016-10-14 02:03
arctic is only officially supported on linux. some people have had limited success with OSX. I haven't heard of anyone using cygwin with any success, have you @jamesblackburn ?

**Comment by bmoscon** [comment] 2017-06-01 18:49
arctic now supported on OSX and Linux. Windows is still not supported. Going to mark this as a dupe of #6

**Closed by bmoscon** 2017-06-01 18:49 UTC
