### ISSUE TITLE
TickStore fails to load correct dtype (int64)

### ISSUE THREAD

**Issue by RayVR** [manahl/arctic#391] opened 2017-07-18 19:35 UTC
#### Arctic Version

```
1.48
```

#### Arctic Store

```
TickStore
```

#### Platform and version

Linux

#### Description of problem and/or code sample that reproduces the issue

Int64 columns are converted to float64 on read.

Document in MongoDB correctly shows the column has a Dtype(t) of 'int64'. Reading the data returns a dataframe with dtype == float64.

**Comment by bmoscon** [comment] 2017-09-04 12:05
can you provide me sample data that exhibits this behavior so I can take a look?

**Comment by bmoscon** [comment] 2017-09-21 21:13
I haven't had any luck reproducing this. If you can provide some sample code / data / etc that reproduces this I can look into it for you.

**Comment by bmoscon** [comment] 2017-12-03 14:39
never heard back on this - closing. If you can provide a small code sample that reproduces the issue i'll look into it.

**Closed** 2017-12-03 14:52 UTC

**Comment by RayVR** [comment] 2017-12-04 21:37
```
import pandas as pd
import numpy as np
from arctic import Arctic, TICK_STORE
from arctic.date import DateRange

rng = np.arange(0, 1e7)
dts = pd.to_datetime(rng, unit=‘m’)
df = pd.DataFrame(index=dts, data=np.array((rng, rng)).T, columns=[‘test_int’, ‘test_float’])
df[‘test_int’] = df[‘test_int’].astype(‘int64’)
print df.dtypes # one int64 column, one float64

# initialize arctic TICK_STORE
store.write(‘test’, df)
out = store.read(‘test’, date_range=DateRange(df.index[0], df.index[-1]))
print out.dtypes # I see two float64 columns here
```

on a mobile device...apologies if it doesn’t run but this should be close enough to replicate.

**Comment by bmoscon** [comment] 2017-12-05 00:36
So I'm not sure what the issue is here, but I don't think its an arctic issue. As you indicated, the df.dtypes says that 'test_int' is a float, but the dtype that comes from head and tail say its of type int64 and the dtype of the series is also int64. So something is clearly off internally in pandas - dtype of the df says the column is float64, dtype of the column says its int64.

**Comment by bmoscon** [comment] 2017-12-05 00:38
heres the code I was using

```python
 rng = np.arange(0, 1e7)
    dts = pd.to_datetime(rng, unit='m')
    df = pd.DataFrame(index=dts, data=np.array((rng, rng)).T, columns=['test_int', 'test_float'])
    df = df.tz_localize('UTC')
    print(df.dtypes)
    print(df['test_int'].head())
    print(df['test_int'].tail())
    df['test_int'] = df['test_int'].astype('int64')
    print(df['test_int'].head())
    print(df['test_int'].tail())

    print(df.dtypes) # one int64 column, one float64

    # initialize arctic TICK_STORE
    tickstore_lib.write('test', df)
    out = tickstore_lib.read('test', date_range=DateRange(df.index[0], df.index[-1]))
    print(out.dtypes) # I see two float64 columns here
    print(df['test_int'].head())
    print(df['test_int'].tail())
    print(df['test_int'].dtype)
```

**Comment by bmoscon** [comment] 2017-12-05 00:39
also tagging @jamesblackburn to see if he has any insights

**Comment by RayVR** [comment] 2019-05-07 04:50
It looks like [this line](https://github.com/manahl/arctic/blob/7c4cc4ecea18c900f52710762fd1e9e8fca2f9ed/arctic/tickstore/tickstore.py#L419) is responsible for converting int64 to float64. 

I think this issue should be open or I can create a new one.

**Comment by RayVR** [comment] 2019-05-07 04:54
Additionally, it looks like column_dtypes will always be empty so existing_dtype will always be None.
