### ISSUE TITLE
Randomly raise Exception: Error decompressing if append many times to a symbol in chunk store

### ISSUE THREAD

**Issue by lionshaw** [manahl/arctic#407] opened 2017-08-29 07:14 UTC
#### Arctic Version

```
arctic (1.51.0)
```

#### Arctic Store

```
ChunkStore
```

#### Platform and version

Red Hat Enterprise Linux Server release 7.2 (Maipo)

#### Description of problem and/or code sample that reproduces the issue

I append daily data to one symbol (write if not exists and set chunk_size = 'A'). 

The data looks like this:

- columns of the DataFrame
```
Index(['beta', 'btop', 'earnyild', 'growth', 'industry', 'leverage',
       'liquidty', 'momentum', 'resvol', 'sid', 'size', 'sizenl'],
      dtype='object')
```

- head of the DataFrame (part)
```
             beta   btop  earnyild  growth  industry  leverage  liquidty 
date                                                                       
2008-12-25  0.200 -0.386    -0.669  -0.432        23    -0.307     0.746   
2008-12-25  0.653  0.048     0.671   0.182        10     0.255     1.097   
2008-12-25 -1.726 -1.105    -1.042  -2.661        22    -0.732    -3.400   
2008-12-25 -0.407  2.840     2.588  -1.505        19    -0.454    -1.137   
2008-12-25  0.931  1.302    -0.946  -0.306        31     3.042    -0.429   
```

- the dtypes
```
beta        float64
btop        float64
earnyild    float64
growth      float64
industry      int64
leverage    float64
liquidty    float64
momentum    float64
resvol      float64
sid           int64
size        float64
sizenl      float64
```

it will randomly raise the following exception (2008-12-25 for example)
```
[2017-08-29 14:17:00] [factor.value] [INFO] update 2008-12-25 barra exposures failed：Error decompressing
[2017-08-29 14:17:00] [factor.value] [ERROR] Traceback (most recent call last):
  File "/home/quant/newalpha/warden/warden/_update_factors.py", line 88, in _update_barra_exposures
    n = update_lib(lib_factors, 'barra_exposures', exposures)
  File "/home/quant/newalpha/warden/warden/utils.py", line 70, in update_lib
    lib.append(symbol, data_to_append, metadata=meta)
  File "/opt/anaconda3/lib/python3.5/site-packages/arctic/chunkstore/chunkstore.py", line 503, in append
    self.__update(sym, item, metadata=metadata, combine_method=SER_MAP[sym[SERIALIZER]].combine, audit=audit)
  File "/opt/anaconda3/lib/python3.5/site-packages/arctic/chunkstore/chunkstore.py", line 415, in __update
    df = self.read(symbol, chunk_range=chunker.to_range(start, end), filter_data=False)
  File "/opt/anaconda3/lib/python3.5/site-packages/arctic/chunkstore/chunkstore.py", line 268, in read
    data = SER_MAP[sym[SERIALIZER]].deserialize(chunks, **kwargs)
  File "/opt/anaconda3/lib/python3.5/site-packages/arctic/serialization/numpy_arrays.py", line 195, in deserialize
    df = pd.concat([self.converter.objify(d, columns) for d in data], ignore_index=not index)
  File "/opt/anaconda3/lib/python3.5/site-packages/arctic/serialization/numpy_arrays.py", line 195, in <listcomp>
    df = pd.concat([self.converter.objify(d, columns) for d in data], ignore_index=not index)
  File "/opt/anaconda3/lib/python3.5/site-packages/arctic/serialization/numpy_arrays.py", line 126, in objify
    d = decompress(doc[DATA][doc[METADATA][LENGTHS][col][0]: doc[METADATA][LENGTHS][col][1] + 1])
  File "/opt/anaconda3/lib/python3.5/site-packages/arctic/_compression.py", line 55, in decompress
    return clz4.decompress(_str)
  File "_compress.pyx", line 121, in _compress.decompress (src/_compress.c:2151)
Exception: Error decompressing

```

It seems that the data was broken and can not be decompressed (for any date range). If I delete the document related to 2008, it can be decompressed again. 

Thx a lot!

**Comment by bmoscon** [comment] 2017-09-04 12:02
I've seen errors like this before, and most were due to data corruption. We have fixed bugs in the LZ4 decompression, but that was many versions before 1.51.

**Comment by lionshaw** [comment] 2017-09-05 01:41
thinks, bmoscon.

I install a fresh mongodb and arctic on windows

```
 [initandlisten] targetMinOS: Windows 7/Windows Server 2008 R2
 [initandlisten] db version v3.4.7
```
```
> pip install arctic
Collecting arctic
  Using cached arctic-1.51.0.tar.gz
...
Building wheels for collected packages: arctic
  Running setup.py bdist_wheel for arctic ... done
Successfully built arctic
Installing collected packages: arctic
Successfully installed arctic-1.51.0
```

and reproduce the exception using the following code. Is there something wrong when I use arctic?

```python
import time

import numpy as np
import pandas as pd
import arctic

store = arctic.Arctic('localhost')

lib_name = 'test.corruption'

try:
    lib = store[lib_name]
except Exception:
    store.initialize_library(lib_name, lib_type=arctic.CHUNK_STORE)
    lib = store[lib_name]


store.set_quota(lib_name, 1024 * 1024 * 1024 * 3)


def generate_data(date):
    df = pd.DataFrame(np.random.randn(3000, 12),
                      columns=['beta', 'btop', 'earnyild', 'growth', 'industry', 'leverage',
                               'liquidty', 'momentum', 'resvol', 'sid', 'size', 'sizenl'])
    df['date'] = date

    date += pd.Timedelta(1, unit='D')

    return date, df


symbol = 'abc'
date = pd.Timestamp('2000-01-01')


while date < pd.Timestamp('2017-09-05'):
    print(date)

    date, df = generate_data(date)

    # write
    if symbol in lib.list_symbols():
        lib.append(symbol, df)
    else:
        lib.write(symbol, df, chunk_size='A')

    time.sleep(0.2)

```

It raises exception as following:

```
2000-02-25 00:00:00
Traceback (most recent call last):
  File "e:/works/repos/warden/test_corruption.py", line 43, in <module>
    lib.append(symbol, df)
  File "D:\Software\Python\Anaconda3\lib\site-packages\arctic\chunkstore\chunkstore.py", line 503, in append
    self.__update(sym, item, metadata=metadata, combine_method=SER_MAP[sym[SERIALIZER]].combine, audit=audit)
  File "D:\Software\Python\Anaconda3\lib\site-packages\arctic\chunkstore\chunkstore.py", line 415, in __update
    df = self.read(symbol, chunk_range=chunker.to_range(start, end), filter_data=False)
  File "D:\Software\Python\Anaconda3\lib\site-packages\arctic\chunkstore\chunkstore.py", line 268, in read
    data = SER_MAP[sym[SERIALIZER]].deserialize(chunks, **kwargs)
  File "D:\Software\Python\Anaconda3\lib\site-packages\arctic\serialization\numpy_arrays.py", line 195, in deserialize
    df = pd.concat([self.converter.objify(d, columns) for d in data], ignore_index=not index)
  File "D:\Software\Python\Anaconda3\lib\site-packages\arctic\serialization\numpy_arrays.py", line 195, in <listcomp>
    df = pd.concat([self.converter.objify(d, columns) for d in data], ignore_index=not index)
  File "D:\Software\Python\Anaconda3\lib\site-packages\arctic\serialization\numpy_arrays.py", line 126, in objify
    d = decompress(doc[DATA][doc[METADATA][LENGTHS][col][0]: doc[METADATA][LENGTHS][col][1] + 1])
  File "D:\Software\Python\Anaconda3\lib\site-packages\arctic\_compression.py", line 55, in decompress
    return clz4.decompress(_str)
  File "_compress.pyx", line 121, in _compress.decompress (src/_compress.c:2151)
Exception: Error decompressing
```

I tried serval times and it corrupts at 2000-02-25 every time.

Thinks for your attention, and this brilliant project!

**Comment by bmoscon** [comment] 2017-09-07 13:28
Windows isnt really supported. In the original description, you indicated it was on linux. Is this issue on windows or on linux?

**Comment by lionshaw** [comment] 2017-09-08 07:10
Found on Linux, and I reproduced it on windows.

Now I reproduced it on Linux again.

```
2000-02-25 00:00:00
Traceback (most recent call last):
  File "test_currption.py", line 43, in <module>
    lib.append(symbol, df)
  File "/opt/anaconda3/lib/python3.5/site-packages/arctic/chunkstore/chunkstore.py", line 503, in append
    self.__update(sym, item, metadata=metadata, combine_method=SER_MAP[sym[SERIALIZER]].combine, audit=audit)
  File "/opt/anaconda3/lib/python3.5/site-packages/arctic/chunkstore/chunkstore.py", line 415, in __update
    df = self.read(symbol, chunk_range=chunker.to_range(start, end), filter_data=False)
  File "/opt/anaconda3/lib/python3.5/site-packages/arctic/chunkstore/chunkstore.py", line 268, in read
    data = SER_MAP[sym[SERIALIZER]].deserialize(chunks, **kwargs)
  File "/opt/anaconda3/lib/python3.5/site-packages/arctic/serialization/numpy_arrays.py", line 195, in deserialize
    df = pd.concat([self.converter.objify(d, columns) for d in data], ignore_index=not index)
  File "/opt/anaconda3/lib/python3.5/site-packages/arctic/serialization/numpy_arrays.py", line 195, in <listcomp>
    df = pd.concat([self.converter.objify(d, columns) for d in data], ignore_index=not index)
  File "/opt/anaconda3/lib/python3.5/site-packages/arctic/serialization/numpy_arrays.py", line 126, in objify
    d = decompress(doc[DATA][doc[METADATA][LENGTHS][col][0]: doc[METADATA][LENGTHS][col][1] + 1])
  File "/opt/anaconda3/lib/python3.5/site-packages/arctic/_compression.py", line 55, in decompress
    return clz4.decompress(_str)
  File "_compress.pyx", line 121, in _compress.decompress (src/_compress.c:2151)
Exception: Error decompressing
```

**Comment by bmoscon** [comment] 2017-09-08 10:19
alright, I'll take a look - thanks for confirming!

**Comment by lionshaw** [comment] 2017-09-10 11:00
thinks, bmoscon.

**Comment by bmoscon** [comment] 2017-09-19 12:05
fixed on master

**Closed by bmoscon** 2017-09-19 12:05 UTC

**Comment by miketkelly** [comment] 2017-10-17 12:17
Hey @bmoscon, I think the fix for this actually exacerbates this issue for pre-existing data. In a library where most chunks are already stored with segment -1, updates to that data will now create new segments at 0 and leave the old -1 segments hanging around.

**Comment by bmoscon** [comment] 2017-10-17 12:26
hm. I could provide a cleaner script that would clean up all the segments (i.e. if any -1s are found, rewrite them as 0s assuming no other ids exist for the segment). I could also change the segment numbers so they start at -1, but that doesnt really solve the issue if you've already written stuff starting from 0. I think its best to leave it as is (everything starts from 0, no more -1 to indicate a singular data segment), but definitely not sure of the best approach to account for old data already written with -1. thoughts? @miketkelly

**Comment by bmoscon** [comment] 2017-10-17 12:29
Also, not 100% sure what the issue is you are seeing. Even if you have written a lot of data starting with segment id -1, you should still be able to read that data, right? The `read` method only sorts the segments, it doesnt expect they start at 0. I think the only functionality that would break is the iterator support since it assumes all segments start at (or rather, every chunk has a segment id 0). Maybe updates wouldnt work, but even then I'm not 100% sure on that since it uses read to get the data you're updating.

**Comment by miketkelly** [comment] 2017-10-17 12:59
The issue I'm seeing is decompression errors. Lots of them. This is caused by read concatenating the -1 and 0 segments. Your best option at this point is probably to make the code compatible with both -1 and 0 based segments. The update code that deletes unused segments could be tweaked to also delete -1 segments. I haven't thought about the iterator code could, but I suppose it could either select the min segment or deduplicate after the query.

**Comment by bmoscon** [comment] 2017-10-17 13:04
How did you get a -1 and a 0 segment? Can you walk me through what operations lead to the symbol being in that state? You obviously had a single segment piece of data already written (hence the segment -1) but where did the segment with id 0 come from?

**Comment by bmoscon** [comment] 2017-10-17 13:07
I ask the above to 1. understand and 2. i didn't think it was possible to break the way you are describing when i made the change, so I'd like to add some unit tests and also be aware of the scenario so i can come up with a correct (hopefully) solution

**Comment by miketkelly** [comment] 2017-10-17 20:23
I ended up with -1 and 0 segments by using the current Arctic version to update data created with an older Arctic version.

[Here](https://gist.github.com/miketkelly/ef813378d75711d23e6c46d260a6d5b5)'s a modified `test_compression` that demonstrates the problem. I change the segment number directly to simulate data created with an older Arctic version. When the subsequent `append` happens, we end up with three segments (-1, 0, 1) rather than two (0, 1).
