### ISSUE TITLE
Cant install on maverick -- OSx

### ISSUE THREAD

**Issue by SlyOne** [manahl/arctic#311] opened 2017-01-03 02:33 UTC
>>>>>$ sudo pip install git+https://github.com/manahl/arctic.git

Collecting git+https://github.com/manahl/arctic.git
  Cloning https://github.com/manahl/arctic.git to /private/tmp/pip-vxBz_x-build
Requirement already satisfied: decorator in /Library/Python/2.7/site-packages (from arctic==1.37.0)
Requirement already satisfied: enum34 in /Library/Python/2.7/site-packages (from arctic==1.37.0)
Requirement already satisfied: lz4 in /Library/Python/2.7/site-packages (from arctic==1.37.0)
Requirement already satisfied: mockextras in /Library/Python/2.7/site-packages (from arctic==1.37.0)
Requirement already satisfied: pandas in /Library/Python/2.7/site-packages (from arctic==1.37.0)
Requirement already satisfied: pymongo>=3.0 in /Library/Python/2.7/site-packages (from arctic==1.37.0)
Requirement already satisfied: python-dateutil in /Library/Python/2.7/site-packages (from arctic==1.37.0)
Requirement already satisfied: pytz in /Library/Python/2.7/site-packages (from arctic==1.37.0)
Requirement already satisfied: tzlocal in /Library/Python/2.7/site-packages (from arctic==1.37.0)
Requirement already satisfied: mock>=0.8.0 in /Library/Python/2.7/site-packages (from mockextras->arctic==1.37.0)
Requirement already satisfied: numpy>=1.7.0 in /Library/Python/2.7/site-packages (from pandas->arctic==1.37.0)
Requirement already satisfied: six>=1.5 in /Library/Python/2.7/site-packages (from python-dateutil->arctic==1.37.0)
Requirement already satisfied: funcsigs>=1; python_version < "3.3" in /Library/Python/2.7/site-packages (from mock>=0.8.0->mockextras->arctic==1.37.0)
Requirement already satisfied: pbr>=0.11 in /Library/Python/2.7/site-packages (from mock>=0.8.0->mockextras->arctic==1.37.0)
Installing collected packages: arctic
  Running setup.py install for arctic ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-vxBz_x-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7blthx-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-intel-2.7
    creating build/lib.macosx-10.9-intel-2.7/arctic
    copying arctic/__init__.py -> build/lib.macosx-10.9-intel-2.7/arctic
    copying arctic/_compression.py -> build/lib.macosx-10.9-intel-2.7/arctic
    copying arctic/_util.py -> build/lib.macosx-10.9-intel-2.7/arctic
    copying arctic/arctic.py -> build/lib.macosx-10.9-intel-2.7/arctic
    copying arctic/auth.py -> build/lib.macosx-10.9-intel-2.7/arctic
    copying arctic/decorators.py -> build/lib.macosx-10.9-intel-2.7/arctic
    copying arctic/exceptions.py -> build/lib.macosx-10.9-intel-2.7/arctic
    copying arctic/hooks.py -> build/lib.macosx-10.9-intel-2.7/arctic
    copying arctic/hosts.py -> build/lib.macosx-10.9-intel-2.7/arctic
    copying arctic/multi_index.py -> build/lib.macosx-10.9-intel-2.7/arctic
    creating build/lib.macosx-10.9-intel-2.7/arctic/chunkstore
    copying arctic/chunkstore/__init__.py -> build/lib.macosx-10.9-intel-2.7/arctic/chunkstore
    copying arctic/chunkstore/_chunker.py -> build/lib.macosx-10.9-intel-2.7/arctic/chunkstore
    copying arctic/chunkstore/chunkstore.py -> build/lib.macosx-10.9-intel-2.7/arctic/chunkstore
    copying arctic/chunkstore/date_chunker.py -> build/lib.macosx-10.9-intel-2.7/arctic/chunkstore
    copying arctic/chunkstore/passthrough_chunker.py -> build/lib.macosx-10.9-intel-2.7/arctic/chunkstore
    creating build/lib.macosx-10.9-intel-2.7/arctic/date
    copying arctic/date/__init__.py -> build/lib.macosx-10.9-intel-2.7/arctic/date
    copying arctic/date/_daterange.py -> build/lib.macosx-10.9-intel-2.7/arctic/date
    copying arctic/date/_generalslice.py -> build/lib.macosx-10.9-intel-2.7/arctic/date
    copying arctic/date/_mktz.py -> build/lib.macosx-10.9-intel-2.7/arctic/date
    copying arctic/date/_parse.py -> build/lib.macosx-10.9-intel-2.7/arctic/date
    copying arctic/date/_util.py -> build/lib.macosx-10.9-intel-2.7/arctic/date
    creating build/lib.macosx-10.9-intel-2.7/arctic/fixtures
    copying arctic/fixtures/__init__.py -> build/lib.macosx-10.9-intel-2.7/arctic/fixtures
    copying arctic/fixtures/arctic.py -> build/lib.macosx-10.9-intel-2.7/arctic/fixtures
    creating build/lib.macosx-10.9-intel-2.7/arctic/scripts
    copying arctic/scripts/__init__.py -> build/lib.macosx-10.9-intel-2.7/arctic/scripts
    copying arctic/scripts/arctic_copy_data.py -> build/lib.macosx-10.9-intel-2.7/arctic/scripts
    copying arctic/scripts/arctic_create_user.py -> build/lib.macosx-10.9-intel-2.7/arctic/scripts
    copying arctic/scripts/arctic_delete_library.py -> build/lib.macosx-10.9-intel-2.7/arctic/scripts
    copying arctic/scripts/arctic_enable_sharding.py -> build/lib.macosx-10.9-intel-2.7/arctic/scripts
    copying arctic/scripts/arctic_fsck.py -> build/lib.macosx-10.9-intel-2.7/arctic/scripts
    copying arctic/scripts/arctic_init_library.py -> build/lib.macosx-10.9-intel-2.7/arctic/scripts
    copying arctic/scripts/arctic_list_libraries.py -> build/lib.macosx-10.9-intel-2.7/arctic/scripts
    copying arctic/scripts/arctic_prune_versions.py -> build/lib.macosx-10.9-intel-2.7/arctic/scripts
    copying arctic/scripts/utils.py -> build/lib.macosx-10.9-intel-2.7/arctic/scripts
    creating build/lib.macosx-10.9-intel-2.7/arctic/serialization
    copying arctic/serialization/__init__.py -> build/lib.macosx-10.9-intel-2.7/arctic/serialization
    copying arctic/serialization/_serializer.py -> build/lib.macosx-10.9-intel-2.7/arctic/serialization
    copying arctic/serialization/numpy_arrays.py -> build/lib.macosx-10.9-intel-2.7/arctic/serialization
    copying arctic/serialization/numpy_records.py -> build/lib.macosx-10.9-intel-2.7/arctic/serialization
    creating build/lib.macosx-10.9-intel-2.7/arctic/store
    copying arctic/store/__init__.py -> build/lib.macosx-10.9-intel-2.7/arctic/store
    copying arctic/store/_ndarray_store.py -> build/lib.macosx-10.9-intel-2.7/arctic/store
    copying arctic/store/_pandas_ndarray_store.py -> build/lib.macosx-10.9-intel-2.7/arctic/store
    copying arctic/store/_pickle_store.py -> build/lib.macosx-10.9-intel-2.7/arctic/store
    copying arctic/store/_version_store_utils.py -> build/lib.macosx-10.9-intel-2.7/arctic/store
    copying arctic/store/audit.py -> build/lib.macosx-10.9-intel-2.7/arctic/store
    copying arctic/store/bitemporal_store.py -> build/lib.macosx-10.9-intel-2.7/arctic/store
    copying arctic/store/version_store.py -> build/lib.macosx-10.9-intel-2.7/arctic/store
    copying arctic/store/versioned_item.py -> build/lib.macosx-10.9-intel-2.7/arctic/store
    creating build/lib.macosx-10.9-intel-2.7/arctic/tickstore
    copying arctic/tickstore/__init__.py -> build/lib.macosx-10.9-intel-2.7/arctic/tickstore
    copying arctic/tickstore/tickstore.py -> build/lib.macosx-10.9-intel-2.7/arctic/tickstore
    copying arctic/tickstore/toplevel.py -> build/lib.macosx-10.9-intel-2.7/arctic/tickstore
    running build_ext
    building 'arctic._compress' extension
    creating build/temp.macosx-10.9-intel-2.7
    creating build/temp.macosx-10.9-intel-2.7/src
    cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/_compress.c -o build/temp.macosx-10.9-intel-2.7/src/_compress.o -fopenmp
    clang: warning: argument unused during compilation: '-fopenmp'
    src/_compress.c:285:10: fatal error: 'omp.h' file not found
    #include "omp.h"
             ^
    1 error generated.
    error: command 'cc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-vxBz_x-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7blthx-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-vxBz_x-build/

**Comment by bmoscon** [comment] 2017-01-04 13:25
OSX is not supported. See issue #14 if you want to try and get it working on your own

**Comment by bmoscon** [comment] 2017-01-04 16:02
closing as this is a duplicate of #14

**Closed by bmoscon** 2017-01-04 16:02 UTC
