### ISSUE TITLE
a bug in _ndarray_store.py in windows?

### ISSUE THREAD

**Issue by testmana2** [manahl/arctic#61] opened 2015-12-18 14:14 UTC
Hi all, maybe there was a bug in _ndarray_store

use pandas dataframe

    index = pd.date_range('1/1/2010', periods=8, tz=mktz())
    df = pd.DataFrame(np.random.randn(8, 3), index=index, columns=list('abc'))
    arctic = Arctic('localhost')
    arctic.initialize_library('nasdaq')
    store_db = arctic.get_library('nasdaq')
    store_db.append('sym001', df, metadata={'source': 'test'})
    
#it's ok...... then read it
    print store_db.read('sym001', date_range=DateRange(start=20100101)).data
# Here  got a exception:
     File "D:\Python27\lib\site-packages\arctic-1.17.0-py2.7-win-amd64.egg\arctic\store\version_store.py", line 321, in read
    date_range=date_range, read_preference=read_preference, **kwargs)
  File "D:\Python27\lib\site-packages\arctic-1.17.0-py2.7-win-amd64.egg\arctic\store\version_store.py", line 366, in _do_read
    data = handler.read(self._arctic_lib, version, symbol, from_version=from_version, **kwargs)
  File "D:\Python27\lib\site-packages\arctic-1.17.0-py2.7-win-amd64.egg\arctic\store\_pandas_ndarray_store.py", line 301, in read
    item = super(PandasDataFrameStore, self).read(arctic_lib, version, symbol, **kwargs)
  File "D:\Python27\lib\site-packages\arctic-1.17.0-py2.7-win-amd64.egg\arctic\store\_pandas_ndarray_store.py", line 197, in read
    date_range=date_range, **kwargs)
  File "D:\Python27\lib\site-packages\arctic-1.17.0-py2.7-win-amd64.egg\arctic\store\_ndarray_store.py", line 170, in read
    return self._do_read(collection, version, symbol, index_range=index_range)
  File "D:\Python27\lib\site-packages\arctic-1.17.0-py2.7-win-amd64.egg\arctic\store\_ndarray_store.py", line 194, in _do_read
    for i, x in enumerate(collection.find(spec, sort=[('segment', pymongo.ASCENDING)],)):
  File "D:\Python27\lib\site-packages\pymongo\cursor.py", line 1097, in next
    if len(self.__data) or self._refresh():
  File "D:\Python27\lib\site-packages\pymongo\cursor.py", line 1019, in _refresh
    self.__read_concern))
  File "D:\Python27\lib\site-packages\pymongo\cursor.py", line 850, in __send_message
    **kwargs)
  File "D:\Python27\lib\site-packages\pymongo\mongo_client.py", line 794, in _send_message_with_response
    exhaust)
  File "D:\Python27\lib\site-packages\pymongo\mongo_client.py", line 805, in _reset_on_error
    return func(*args, **kwargs)
  File "D:\Python27\lib\site-packages\pymongo\server.py", line 108, in send_message_with_response
    set_slave_okay, sock_info.is_mongos, use_find_cmd)
  File "D:\Python27\lib\site-packages\pymongo\message.py", line 275, in get_message
    spec, self.fields, self.codec_options)
bson.errors.InvalidDocument: Cannot encode object: 7
    
It looked very stranger...
I checked this question a whole day....  and I found the problem was:
        spec = {'symbol': symbol,
                'parent': version.get('base_version_id', version['_id']),
                'segment': {'$lt': to_index}
                }
        if from_index:
----->
            spec['segment']['$gte'] = from_index

I change this line:
     spec['segment']['$gte'] = from_index 
to 
     spec['segment']['$gte'] = long(from_index)

because the type(from_index) was numpy.int64, it was not compatible with pymongo in windows64,
the solution was use python type instead of numpy type, here was the two way to do this:
1.  to_index.item()    and    from_index.item()
2.  long(to_index())   and    long(from_index)

Were there some better solution?

**Comment by bmoscon** [comment] 2015-12-19 13:28
since Arctic isnt really supported on Windows (yet) there could be a number of other issues and possible solutions

**Comment by jamesblackburn** [comment] 2015-12-30 10:27
As @bmoscon said we need some work to support Windows.  Help is wanted (PRs, etc.) on this front.  Closing this as a duplicate of #6

**Closed by jamesblackburn** 2015-12-30 10:27 UTC
