### ISSUE TITLE
how_to_use_arctic.py fails with SyntaxError: unexpected EOF while parsing on library.read()

### ISSUE THREAD

**Issue by jeffneuen** [manahl/arctic#37] opened 2015-10-28 15:12 UTC
Attempting to run the demo as a test, and getting errors on library.read().  Also, I get an error the first time I run store.initialize_library('username.scratch'), but the second time it did works.  I did have to make the following change to get import Arctic to run:

store/_version_store_utils.py, line 66:    if pd.__version__.startswith("0.14"):

See paste of output included the EOF error below.  I'm not sure if it's a numpy bug or arctic, but I'm not sure where to go from here.

Python 2.7.10 |Anaconda 2.3.0 (64-bit)| (default, Oct 19 2015, 18:04:42) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> from arctic import Arctic
>>> from datetime import datetime as dt
>>> import pandas as pd
>>> store = Arctic('localhost')
>>> store.list_libraries()
[u'NASDAQ', u'username.scratch']
>>> store.initialize_library('username.scratch')
No handlers could be found for logger "arctic.store.version_store"
>>> store.initialize_library('username.scratch')
>>> library = store['username.scratch']
>>> df = pd.DataFrame({'prices': [1, 2, 3]},[dt(2014, 1, 1), dt(2014, 1, 2), dt(2014, 1, 3)])
>>> library.write('SYMBOL', df)
VersionedItem(symbol=SYMBOL,library=arctic_username.scratch,data=<type 'NoneType'>,version=19,metadata=None
>>> library.read('SYMBOL')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jeff/anaconda/lib/python2.7/site-packages/arctic/store/version_store.py", line 319, in read
    date_range=date_range, read_preference=read_preference, **kwargs)
  File "/home/jeff/anaconda/lib/python2.7/site-packages/arctic/store/version_store.py", line 363, in _do_read
    data = handler.read(self._arctic_lib, version, symbol, from_version=from_version, **kwargs)
  File "/home/jeff/anaconda/lib/python2.7/site-packages/arctic/store/_pandas_ndarray_store.py", line 279, in read
    item = super(PandasDataFrameStore, self).read(arctic_lib, version, symbol, **kwargs)
  File "/home/jeff/anaconda/lib/python2.7/site-packages/arctic/store/_pandas_ndarray_store.py", line 193, in read
    date_range=date_range, **kwargs)
  File "/home/jeff/anaconda/lib/python2.7/site-packages/arctic/store/_ndarray_store.py", line 180, in read
    return self._do_read(collection, version, symbol, index_range=index_range)
  File "/home/jeff/anaconda/lib/python2.7/site-packages/arctic/store/_ndarray_store.py", line 219, in _do_read
    dtype = self._dtype(version['dtype'], version.get('dtype_metadata', {}))
  File "/home/jeff/anaconda/lib/python2.7/site-packages/arctic/store/_ndarray_store.py", line 139, in _dtype
    return np.dtype(string, metadata=metadata)
  File "/home/jeff/anaconda/lib/python2.7/site-packages/numpy/core/_internal.py", line 191, in _commastring
    newitem = (dtype, eval(repeats))
  File "<string>", line 1
    (
    ^
SyntaxError: unexpected EOF while parsing
>>>

**Comment by jamesblackburn** [comment] 2015-10-28 17:40
I observed this too over the last couple of days with numpy 1.10.1:
https://circleci.com/gh/manahl/arctic/131

It seems to be a behaviour change / breakage in numpy:
`File "/home/jeff/anaconda/lib/python2.7/site-packages/numpy/core/_internal.py", line 191, in _commastring`


Downgrading numpy seems to fix it. Not yet had a chance to debug what's changed in the new version.

**Comment by jeffneuen** [comment] 2015-10-28 18:20
Cool, thanks for the update.  Downgrading numpy breaks other things for me unfortunately, will keep an eye out for the fix.

**Comment by llazzaro** [comment] 2015-11-11 04:14
Hi! I also hit this issue. seems to be a serialisation issue of the dtype. 
numpy version is 1.10.1

**Comment by denisvolokh** [comment] 2015-12-01 08:41
any updates on this issue?

**Comment by llazzaro** [comment] 2015-12-01 17:13
I think a have a fix here https://github.com/llazzaro/arctic/commit/009ef7ea5ed391cdc4439c02e29d5e4e1a17a8fe
I will try to do a pull request tonight.

could you cherry pick that commit and test if it works?

**Comment by denisvolokh** [comment] 2015-12-02 02:38
Hi, 

I have bad revision when I do "git cherry-pick 009ef7"

`git cherry-pick 009ef7`
`fatal: bad revision '009ef7'`

Am I doing it wrong way?

**Comment by llazzaro** [comment] 2015-12-02 02:53
The commit is in my fork, to apply it:
git remote add llazzaro https://github.com/llazzaro/arctic.git
git fetch llazzaro
git cherry-pick -n 009ef7

**Comment by denisvolokh** [comment] 2015-12-02 05:04
How to install your fix with pip?

**Comment by denisvolokh** [comment] 2015-12-02 06:02
Unfortunately your fix did not work.

`df = pd.DataFrame({"prices" : [1,2,3]}, [dt(2014, 1, 1), dt(2014, 1,2), dt(2014, 1,3)])`
`library.write("SYMBOL", df)`
`library.read('SYMBOL')`

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-7-8ddd3a5b103a> in <module>()
----> 1 library.read('SYMBOL')

/usr/local/lib/python2.7/dist-packages/arctic/store/version_store.pyc in read(self, symbol, as_of, date_range, from_version, allow_secondary, **kwargs)
    319             _version = self._read_metadata(symbol, as_of=as_of, read_preference=read_preference)
    320             return self._do_read(symbol, _version, from_version,
--> 321                                  date_range=date_range, read_preference=read_preference, **kwargs)
    322         except (OperationFailure, AutoReconnect) as e:
    323             # Log the exception so we know how often this is happening

/usr/local/lib/python2.7/dist-packages/arctic/store/version_store.pyc in _do_read(self, symbol, version, from_version, **kwargs)
    364     def _do_read(self, symbol, version, from_version=None, **kwargs):
    365         handler = self._read_handler(version, symbol)
--> 366         data = handler.read(self._arctic_lib, version, symbol, from_version=from_version, **kwargs)
    367         if data is None:
    368             raise NoDataFoundException("No data found for %s in library %s" % (symbol, self._arctic_lib.get_name()))

/usr/local/lib/python2.7/dist-packages/arctic/store/_pandas_ndarray_store.pyc in read(self, arctic_lib, version, symbol, **kwargs)
    297     def read(self, arctic_lib, version, symbol, **kwargs):
    298         item = super(PandasDataFrameStore, self).read(arctic_lib, version, symbol, **kwargs)
--> 299         return self.from_records(item)
    300 
    301 

/usr/local/lib/python2.7/dist-packages/arctic/store/_pandas_ndarray_store.pyc in from_records(self, recarr)
    271 
    272     def from_records(self, recarr):
--> 273         index = self._index_from_records(recarr)
    274         column_fields = [x for x in recarr.dtype.names if x not in recarr.dtype.metadata['index']]
    275         if len(recarr) == 0:

/usr/local/lib/python2.7/dist-packages/arctic/store/_pandas_ndarray_store.pyc in _index_from_records(self, recarr)
     62 
     63     def _index_from_records(self, recarr):
---> 64         index = recarr.dtype.metadata['index']
     65         rtn = MultiIndex.from_arrays([recarr[str(i)] for i in index], names=index)
     66 

KeyError: 'index'

**Comment by bmoscon** [comment] 2015-12-02 12:12
it looks like the fix did partially work. It seems to have just moved you on to a new error

**Comment by llazzaro** [comment] 2015-12-03 00:48
thank you for the test case. when I have some free time I will check this bug again

**Comment by bmoscon** [comment] 2015-12-04 14:41
@denisvolokh if you give me a better idea of how you hit this issue I can try and reproduce it this weekend and then get it fixed.

**Comment by denisvolokh** [comment] 2015-12-04 14:54
Hi, 

I have created container with jupyter and arctic and tried code from how_to_use_arctic.py file. 
[Dockerfile.txt](https://github.com/manahl/arctic/files/52142/Dockerfile.txt)

It crashing in the line 31:
`library.read('SYMBOL')`

Hope it will help to reproduce this issue. 

Thank you for your help.

**Comment by bmoscon** [comment] 2015-12-04 15:09
ok, great. I'll try and get this case reproduced and will let you know how I fare.

**Comment by bmoscon** [comment] 2015-12-05 16:56
I got the container up and running @denisvolokh but I cant connect to the notebook for anything. I've tried all the IP addresses in my ifconfig (with port 8888) to no avail. Any suggestions?

**Comment by bmoscon** [comment] 2015-12-05 17:06
this is the output when I spin up the container:

[I 16:49:13.407 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[W 16:49:13.427 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 16:49:13.427 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[I 16:49:13.430 NotebookApp] Serving notebooks from local directory: /notebooks
[I 16:49:13.430 NotebookApp] 0 active kernels 
[I 16:49:13.430 NotebookApp] The IPython Notebook is running at: http://[all ip addresses on your system]:8888/
[I 16:49:13.430 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 16:49:13.430 NotebookApp] No web browser found: could not locate runnable browser.

**Comment by bmoscon** [comment] 2015-12-05 18:40
I eventually gave up on docker, but have now been successful in reproducing all the issues mentioned in this thread using anaconda with latest NumPy and Pandas. I've confirmed that if you roll back numpy to 1.9.2 and Pandas to 0.16.2 that the issue goes away (you'll need to remove the libraries from Mongodb since they will have bad data written to them that will cause the error). Now that I have a working case and a broken case, I can spend some time figuring this out, and hopefully resolving it. Will keep you posted @jeffneuen @denisvolokh

**Comment by bmoscon** [comment] 2015-12-05 20:25
Ok, discovered the issue. There is a bug, or at least a change in behavior in Numpy. see issue https://github.com/numpy/numpy/issues/6771

I have a fix for this, but I'm going to need to test it a bit more. Should have a pull req open late tonight or tomorrow.

**Comment by denisvolokh** [comment] 2015-12-06 07:10
Thank you for keeping us posted.

`docker-machine ip default` should give you right IP address for your
notebooks.

Kind regards,
Denis Volokh

**Comment by jamesblackburn** [comment] 2015-12-11 16:36
These issues should now be fixed. Do let us know if not.

**Closed by jamesblackburn** 2015-12-11 16:36 UTC
